// <auto-generated />
namespace J_LearningSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixTitleForVideo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixTitleForVideo));
        
        string IMigrationMetadata.Id
        {
            get { return "201605061530090_FixTitleForVideo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
